/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia.pkg5;

import javax.swing.JOptionPane;

/**
 *
 * @author Diegp
 */
public class APP2 extends javax.swing.JFrame {

    /**
     * Creates new form APP2
     */
    public APP2() {
        initComponents();
       
        
        btnInsertar.setEnabled(false);
        panelito1.setVisible(false);
        
    }
     String[] letras = new String[10];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnProcesarMenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panelito1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtArray = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelito2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPegar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOpcion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(590, 420));
        setMinimumSize(new java.awt.Dimension(590, 420));
        setPreferredSize(new java.awt.Dimension(590, 420));
        getContentPane().setLayout(null);

        jLabel4.setText("Ingrese la opción que Desea:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(29, 22, 206, 14);

        btnProcesarMenu.setText("Procesar");
        btnProcesarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcesarMenu);
        btnProcesarMenu.setBounds(122, 179, 106, 23);

        jLabel5.setText("0. Salir");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(29, 146, 188, 14);

        jLabel6.setText("ingrese las letras (10 en total)");

        txtArray.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtArrayKeyTyped(evt);
            }
        });

        btnInsertar.setText("insertar+");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelito1Layout = new javax.swing.GroupLayout(panelito1);
        panelito1.setLayout(panelito1Layout);
        panelito1Layout.setHorizontalGroup(
            panelito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelito1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txtArray, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(panelito1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelito1Layout.setVerticalGroup(
            panelito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelito1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(panelito1);
        panelito1.setBounds(106, 230, 346, 104);

        jLabel1.setText("1.Para ingresar las letras");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(29, 54, 391, 29);

        jLabel7.setText("las letras ingresadas son:");

        txtPegar.setText("                        ");

        javax.swing.GroupLayout panelito2Layout = new javax.swing.GroupLayout(panelito2);
        panelito2.setLayout(panelito2Layout);
        panelito2Layout.setHorizontalGroup(
            panelito2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelito2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtPegar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelito2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelito2Layout.setVerticalGroup(
            panelito2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelito2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtPegar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(panelito2);
        panelito2.setBounds(386, 22, 180, 165);

        jLabel2.setText("2. Ordenar de manera Ascendente ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(29, 89, 239, 14);

        jLabel3.setText("3. Mostrar letras Ingresadas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(29, 114, 257, 14);

        txtOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpcionActionPerformed(evt);
            }
        });
        txtOpcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOpcionKeyTyped(evt);
            }
        });
        getContentPane().add(txtOpcion);
        txtOpcion.setBounds(29, 180, 75, 20);

        jButton1.setText("Regresar para ver las demas Aplicaciones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(164, 345, 261, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/letras.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 580, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void limpiar() {

    }

    public void burbuja() {
        //metodo de la burbuja para ordenar el array
        for (int j = 0; j < 4; j++) {
            for (int i = 0; i < 4 - j; i++) {
                if (letras[i].compareTo(letras[i + 1]) > 0) {
                    String aux;
                    aux = letras[i];
                    letras[i] = letras[i + 1];
                    letras[i + 1] = aux;
                }
            }
        }

    }

    public void impresion() {
        String cadena="";
        for (int i = 0; i < letras.length; i++) {
            cadena=cadena+letras[i];
         
          
         //   System.out.println(letras[i]);
        }
           txtPegar.setText(cadena);
    }
    private void btnProcesarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarMenuActionPerformed

        String eleccion;
        int num;

        eleccion = txtOpcion.getText();
        num = Integer.parseInt(eleccion);
        txtOpcion.setText("");

        if (num < 0 || num > 3) {
            JOptionPane.showMessageDialog(null, "ingrese una opcion valida");

        } else {

            switch (num) {
                case 1:
                txtArray.setText("");
                txtArray.setEnabled(true);
                btnInsertar.setEnabled(false);
                panelito1.setVisible(true);
                btnProcesarMenu.setEnabled(false);
                txtOpcion.setEnabled(false);
                txtPegar.setText("");
                break;
                case 2:

                if(txtArray.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"aun no se ingresa una cadena de texto para ordenar!");
                }else{
                    burbuja();
                    JOptionPane.showMessageDialog(null, "serie de letras ordenadas !");
                    btnProcesarMenu.setEnabled(true);
                    txtOpcion.setEnabled(true);
                    txtPegar.setText("");

                }
                break;
                case 3:
                impresion();

                break;
                case 0:
                System.exit(0);
                break;
            }
        }
    }//GEN-LAST:event_btnProcesarMenuActionPerformed

    private void txtArrayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArrayKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
        } else {
            evt.consume();
        }
        if (txtArray.getText().length() >= 10) {
            evt.consume();//validacion de maximo de letras

        }
        if (txtArray.getText().length() > 9) {
            btnInsertar.setEnabled(true);
            txtArray.setEnabled(false);
        }
    }//GEN-LAST:event_txtArrayKeyTyped

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        for (int i = 0; i < 10; i++) {
            letras[i] = "";
        }

        int i;
        String letritas = txtArray.getText(); //para recorrer la cadena de texto y despues leerla caracter --
        for (i = 0; i < 10; i++) {                   //por caracter y ingresarlo en un array string
            letras[i] = Character.toString(letritas.charAt(i));
        }

        panelito1.setVisible(false);//ocultar el panel al presionar el boton
        btnProcesarMenu.setEnabled(true);
        txtOpcion.setEnabled(true);
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void txtOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpcionActionPerformed

    }//GEN-LAST:event_txtOpcionActionPerformed

    private void txtOpcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOpcionKeyTyped
        //validacion para que ingrese letras
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtOpcionKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
                dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APP2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnProcesarMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panelito1;
    private javax.swing.JPanel panelito2;
    private javax.swing.JTextField txtArray;
    private javax.swing.JTextField txtOpcion;
    private javax.swing.JLabel txtPegar;
    // End of variables declaration//GEN-END:variables
}
