/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia.pkg5;

import javax.swing.JOptionPane;

/**
 *
 * @author Diegp
 */
public class frm4lados extends javax.swing.JFrame {

    /**
     * Creates new form frm4lados
     */
    public frm4lados() {
        initComponents();
       
        txtl2.setEnabled(false);
        txtl3.setEnabled(false);
        txtl4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtl1 = new javax.swing.JTextField();
        txtl2 = new javax.swing.JTextField();
        txtl3 = new javax.swing.JTextField();
        txtl4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lbldiagonal4 = new javax.swing.JLabel();
        lblarea4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 485));
        setMinimumSize(new java.awt.Dimension(500, 485));
        setPreferredSize(new java.awt.Dimension(500, 485));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Bienvenido a la app para calcular diagonal y aerea de una figura de 4 lados");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 490, 42);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Ingrese el tamaño del primer Lado");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 230, 21);

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Ingrese el tamaño del segundo Lado");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 230, 19);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Ingrese el tamaño del tercer Lado");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 220, 23);

        jLabel5.setBackground(new java.awt.Color(153, 255, 153));
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Ingrese el tamaño del cuarto Lado");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 240, 23);

        txtl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtl1ActionPerformed(evt);
            }
        });
        txtl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtl1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtl1KeyTyped(evt);
            }
        });
        getContentPane().add(txtl1);
        txtl1.setBounds(261, 88, 107, 20);

        txtl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtl2ActionPerformed(evt);
            }
        });
        txtl2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtl2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtl2KeyTyped(evt);
            }
        });
        getContentPane().add(txtl2);
        txtl2.setBounds(261, 124, 107, 20);

        txtl3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtl3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtl3KeyTyped(evt);
            }
        });
        getContentPane().add(txtl3);
        txtl3.setBounds(260, 160, 107, 20);

        txtl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtl4ActionPerformed(evt);
            }
        });
        txtl4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtl4KeyTyped(evt);
            }
        });
        getContentPane().add(txtl4);
        txtl4.setBounds(261, 189, 107, 20);

        jButton1.setText("Calcular ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 250, 100, 23);

        jLabel6.setText("El area es :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(162, 276, 54, 14);

        jLabel7.setText("La diagonal es:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(162, 308, 72, 14);

        jButton2.setText("Regresar a las funciones de la APP1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 370, 260, 23);
        getContentPane().add(lbldiagonal4);
        lbldiagonal4.setBounds(290, 308, 144, 25);
        getContentPane().add(lblarea4);
        lblarea4.setBounds(290, 265, 104, 25);

        jLabel8.setText("PRESIONAR ENTER PARA PASAR A LAS SIGUIENTE CASILLA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(125, 48, 290, 14);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mate2.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 500, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtl2ActionPerformed

    private void txtl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtl1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double l1=Double.parseDouble(txtl1.getText());
         double l2=Double.parseDouble(txtl2.getText());
          double l3=Double.parseDouble(txtl3.getText());
           double l4=Double.parseDouble(txtl4.getText());
           int figura = 0;
           switch (figura){
               
               case 0 :{
                   if(l1==l2 && l1==l3 && l1==l4){
                       lblarea4.setText(String.valueOf(l1*l1));
                       lbldiagonal4.setText(String.valueOf(Math.sqrt((l1*l1)+(l1*l1))));
                   }
                   else if (l1==l3 && l2==l4 ){
                       lblarea4.setText(String.valueOf(l1*l2));
                       lbldiagonal4.setText(String.valueOf(Math.sqrt((l1*l1)+(l2*l2))));
                   }else if (l2==l3 || l1!=l4 ){
                       lblarea4.setText(String.valueOf(((l1+l4)*3)/2));
                       lbldiagonal4.setEnabled(false);
                   }
                   break;
               }
               
               
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtl4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtl4ActionPerformed

    private void txtl1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtl1KeyTyped
         char c=evt.getKeyChar();
            
        
                
          if(Character.isLetter(c)) {
              getToolkit().beep();
              
              evt.consume();
              
              JOptionPane.showMessageDialog(rootPane,"Ingresa Solo Numeros");
              
          
        
        }     
    }//GEN-LAST:event_txtl1KeyTyped

    private void txtl2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtl2KeyTyped
        char c=evt.getKeyChar();
            
        
                
          if(Character.isLetter(c)) {
              getToolkit().beep();
              
              evt.consume();
              
              JOptionPane.showMessageDialog(rootPane,"Ingresa Solo Numeros");
              
          
        
        }     
    }//GEN-LAST:event_txtl2KeyTyped

    private void txtl3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtl3KeyTyped
         char c=evt.getKeyChar();
            
        
                
          if(Character.isLetter(c)) {
              getToolkit().beep();
              
              evt.consume();
              
              JOptionPane.showMessageDialog(rootPane,"Ingresa Solo Numeros");
              
          
        
        }     
    }//GEN-LAST:event_txtl3KeyTyped

    private void txtl4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtl4KeyTyped
         char c=evt.getKeyChar();
            
        
                
          if(Character.isLetter(c)) {
              getToolkit().beep();
              
              evt.consume();
              
              JOptionPane.showMessageDialog(rootPane,"Ingresa Solo Numeros");
              
          
        
        }     
    }//GEN-LAST:event_txtl4KeyTyped

    private void txtl1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtl1KeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER){
       txtl2.requestFocus();
       txtl2.setEnabled(true);}
    }//GEN-LAST:event_txtl1KeyPressed

    private void txtl2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtl2KeyPressed
       if (evt.getKeyCode()==evt.VK_ENTER){
       txtl3.requestFocus();
       txtl3.setEnabled(true);}
    }//GEN-LAST:event_txtl2KeyPressed

    private void txtl3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtl3KeyPressed
       if (evt.getKeyCode()==evt.VK_ENTER){
       txtl4.requestFocus();
       txtl4.setEnabled(true);}
       
    }//GEN-LAST:event_txtl3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm4lados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm4lados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm4lados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm4lados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm4lados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblarea4;
    private javax.swing.JLabel lbldiagonal4;
    private javax.swing.JTextField txtl1;
    private javax.swing.JTextField txtl2;
    private javax.swing.JTextField txtl3;
    private javax.swing.JTextField txtl4;
    // End of variables declaration//GEN-END:variables
}
