/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia.pkg5;

import javax.swing.JOptionPane;

/**
 *
 * @author Diegp
 */
public class Frmcubo extends javax.swing.JFrame {

    /**
     * Creates new form Frmcubo
     */
    public Frmcubo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdiagonalcubo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btncalcularcubo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblarista = new javax.swing.JLabel();
        lblvolumen = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(420, 300));
        setMinimumSize(new java.awt.Dimension(420, 300));
        setPreferredSize(new java.awt.Dimension(420, 300));
        getContentPane().setLayout(null);

        jLabel1.setText("Volumen de un Cubo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(144, 11, 98, 14);

        jLabel2.setText("Ingrese la Diagonal");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 46, 152, 14);

        txtdiagonalcubo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdiagonalcuboKeyTyped(evt);
            }
        });
        getContentPane().add(txtdiagonalcubo);
        txtdiagonalcubo.setBounds(180, 33, 67, 30);

        jLabel3.setText("Resultado de la arista es:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 81, 152, 14);

        btncalcularcubo.setText("Calcular");
        btncalcularcubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularcuboActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcularcubo);
        btncalcularcubo.setBounds(146, 159, 90, 23);

        jLabel4.setText("Resultado de volumen es: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 122, 152, 14);

        jButton1.setText("Regresar a otras variables del APP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(77, 214, 223, 23);

        lblarista.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblarista.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblarista);
        lblarista.setBounds(180, 81, 157, 23);

        lblvolumen.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblvolumen.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblvolumen);
        lblvolumen.setBounds(180, 122, 157, 19);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mate3.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcularcuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularcuboActionPerformed
        double diagonal=Double.parseDouble(txtdiagonalcubo.getText());
        lblarista.setText(String.valueOf(diagonal/1.414213562));
       double arista=Double.parseDouble(lblarista.getText());
        lblvolumen.setText(String.valueOf(arista*arista*arista));
    }//GEN-LAST:event_btncalcularcuboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtdiagonalcuboKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiagonalcuboKeyTyped
        char c=evt.getKeyChar();
            
        
                
          if(Character.isLetter(c)) {
              getToolkit().beep();
              
              evt.consume();
              
              JOptionPane.showMessageDialog(rootPane,"Ingresa Solo Numeros");
              
          
        
        }     
    }//GEN-LAST:event_txtdiagonalcuboKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmcubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmcubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmcubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmcubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmcubo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcularcubo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblarista;
    private javax.swing.JLabel lblvolumen;
    private javax.swing.JTextField txtdiagonalcubo;
    // End of variables declaration//GEN-END:variables
}
