/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia.pkg5;

import javax.swing.JOptionPane;

/**
 *
 * @author Diegp
 */
public class frmesfera extends javax.swing.JFrame {

    /**
     * Creates new form frmesfera
     */
    public frmesfera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtradesfera = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btncalcularesfera = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblvolumenesfera = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel1.setText("Volumen de una Esfera");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 180, 17);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel2.setText("Ingrese el radio de la esfera");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 190, 24);

        txtradesfera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtradesferaKeyTyped(evt);
            }
        });
        getContentPane().add(txtradesfera);
        txtradesfera.setBounds(210, 40, 111, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel3.setText("Volumende la esfera es igual a:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(51, 102, 188, 17);

        btncalcularesfera.setText("Calcular");
        btncalcularesfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularesferaActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcularesfera);
        btncalcularesfera.setBounds(140, 160, 120, 23);

        jButton1.setText("Regresar a las otras funciones del APP 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 210, 320, 23);

        lblvolumenesfera.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblvolumenesfera.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblvolumenesfera);
        lblvolumenesfera.setBounds(260, 100, 105, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mate3.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 420, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcularesferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularesferaActionPerformed
        double radio=Double.parseDouble(txtradesfera.getText());
        lblvolumenesfera.setText(String.valueOf(4.186666667*radio*radio*radio));
    }//GEN-LAST:event_btncalcularesferaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtradesferaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtradesferaKeyTyped
       char c=evt.getKeyChar();
            
        
                
          if(Character.isLetter(c)) {
              getToolkit().beep();
              
              evt.consume();
              
              JOptionPane.showMessageDialog(rootPane,"Ingresa Solo Numeros");}
    }//GEN-LAST:event_txtradesferaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmesfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmesfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmesfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmesfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmesfera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcularesfera;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblvolumenesfera;
    private javax.swing.JTextField txtradesfera;
    // End of variables declaration//GEN-END:variables
}
